### ISSUE TITLE
No installation instructions for Home Assistant?

### ISSUE THREAD

**Issue by PiRune** [michaelarnauts/cec-mqtt-bridge#29]
I’ve been using your great tool with Node-RED for a while, but after recently moving from Raspbian to Hassio (HassOS), I don’t know how to install it? 

I still want to use with Node-RED, but installed on Hassio (HassOS) rather than Raspbian.

If this is not possible what is the best way of sending and receiving raw cec commands with Hassio.

**Comment by michaelarnauts** [comment]
I think there is a hdmi_cec component in Hass for this.

**Comment by PiRune** [comment]
Thanks for your swift reply. I've tried to find it, but was not able to. Can you link to the one you're thinking of?

https://www.home-assistant.io/integrations/hdmi_cec does not seem to support listening for or sending raw commands...

**Comment by depuits** [comment]
I also use this with home assistant because when using the home assistant component the device you want to control needs to be connected to the home assistant device.

I use a simple [mqtt switch component](https://www.home-assistant.io/integrations/switch.mqtt/) to power the tv.

```
switch:
  - platform: mqtt
    name: Living Room TV
    command_topic: 'mqttTopic/cec/0/cmd'
    payload_on: 'on'
    payload_off: 'off'
    state_topic: 'mqttTopic/cec/0'
    availability_topic: 'mqttTopic/bridge/status'
```
