### ISSUE TITLE
ERROR: Could not initialise CEC: Could not connect to cec adapter

### ISSUE THREAD

**Issue by depuits** [michaelarnauts/cec-mqtt-bridge#34]
I keep getting this error when trying to start the application. I've tried changing the port in the config but the error remains. 

I've tried the default `port=RPI`. Using `cec-client -l` I got following output:
```
libCEC version: 6.0.2, compiled on Linux-5.10.63-v8+ ... , features: P8_USB, DRM, P8_detect, randr, RPi, Exynos, Linux, AOCEC
Found devices: 1

device:              1
com port:            /dev/cec0
vendor id:           0000
product id:          0000
firmware version:    0
type:                Linux
```
What to me looked like I should use port `/dev/cec0` but with the same result.

I followed the setup as described [here](https://selfhostedhome.com/make-a-dumb-tv-smart-using-mqtt-and-cec/). Only things different is that is don't have the `/dev/vcsm` and I had to change the `dockerfile` as in https://github.com/AlecLetourneau/cec-mqtt-bridge/pull/1.

Any idea how to resolve this issue?

**Comment by michaelarnauts** [comment]
When running on docker, I use the following docker-compose.yml file.


```
version: '2'
services:
  cec-mqtt-bridge:
    build:
      context: src/
    restart: unless-stopped
    environment:
      TZ: "Europe/Brussels"
    devices:
      - /dev/vchiq
    volumes:
      - ./src:/usr/src/app
```

Maybe you need to map the `/dev/vchiq` device?
